// Crops the white margin off the reference logo and writes it into
// src/lib/docx/logo.ts (base64), so the letterhead has no file to load at
// runtime. Usage: npm run crop-logo [-- path/to/logo.png]
import { readdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import sharp from "sharp";

const refDir = path.resolve("..", "reference");
const input =
  process.argv[2] ??
  path.join(refDir, readdirSync(refDir).find((f) => /\.png$/i.test(f)) ?? "");
if (!/\.png$/i.test(input)) {
  console.error("No PNG found. Pass the logo path: npm run crop-logo -- path/to/logo.png");
  process.exit(1);
}

// trim() removes the near-white border (threshold handles off-white/JPEG noise).
const original = await sharp(input).metadata();
const trimmed = await sharp(input).trim({ background: "#ffffff", threshold: 20 }).png().toBuffer();
const meta = await sharp(trimmed).metadata();
// Keep the file small: letterhead logos never need more than ~900px.
const out = meta.width > 900 ? await sharp(trimmed).resize({ width: 900 }).png({ compressionLevel: 9 }).toBuffer() : trimmed;
const { width, height } = await sharp(out).metadata();

writeFileSync(
  "src/lib/docx/logo.ts",
  `// Tightly cropped logo for the letterhead, generated by \`npm run crop-logo\`
// from ${path.relative(path.resolve(".."), input)}. Do not edit by hand.
export const LOGO: { base64: string; width: number; height: number } | null = {
  width: ${width},
  height: ${height},
  base64: "${out.toString("base64")}",
};
`,
);
console.log(`Cropped ${path.basename(input)}: ${original.width}x${original.height} → ${width}x${height}, ${out.length} bytes`);
