// Tightly cropped logo for the letterhead, generated by
// `npm run crop-logo` from reference/<logo>.png. Null until the reference
// logo is added to the repo; the letterhead then prints the company name only.
export const LOGO: { base64: string; width: number; height: number } | null = null;
